import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { generateKeyPairSync, randomBytes, sign } from 'node:crypto';
import { Store } from '../server/store.js';
import { createApp } from '../server/app.js';
import { canonicalMessage, commitmentHash, score } from '../server/logic.js';
import { SuiAnchor } from '../server/sui.js';

test('prospective full-slate exam: signed commit, delayed reveal, exact score, verification and missed attempt', async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'proven-test-'));
  t.after(() => fs.rm(dir, { recursive: true, force: true }));
  const store = await new Store(dir).init();
  let now = Date.now();
  const app = createApp({ store, chain: { enabled: false, verifyObject: async () => ({ status: 'not_anchored' }) }, env: { ADMIN_TOKEN: 'test-secret', DEMO_MODE: 'false' }, clock: () => now });
  const server = app.listen(0, '127.0.0.1');
  t.after(() => server.close());
  await new Promise(resolve => server.once('listening', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const req = async (method, url, body, admin = false) => {
    const response = await fetch(base + url, { method, headers: { 'Content-Type': 'application/json', ...(admin ? { Authorization: 'Bearer test-secret' } : {}) }, body: body && JSON.stringify(body) });
    return { status: response.status, body: await response.json() };
  };
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const publicDer = publicKey.export({ format: 'der', type: 'spki' }).toString('base64');
  const signed = text => sign(null, Buffer.from(text), privateKey).toString('base64');
  const name = 'Athena'; const modelVersion = 'athena-1';
  const agent = await req('POST', '/api/agents', { name, modelVersion, publicKey: publicDer, signature: signed(canonicalMessage('register', [name, modelVersion])) });
  assert.equal(agent.status, 201);
  const noAdmin = await req('POST', '/api/admin/exams', {});
  assert.equal(noAdmin.status, 401);
  const exam = await req('POST', '/api/admin/exams', { title: 'BTC fixed exam', domain: 'BTC', cutoffAt: new Date(now + 120000).toISOString(), revealUntil: new Date(now + 240000).toISOString(), resolveAfter: new Date(now + 360000).toISOString(), questions: [{ text: 'BTC above threshold A at midnight?', source: 'fixed price source A', baselineBps: 5000 }, { text: 'BTC above threshold B at midnight?', source: 'fixed price source B', baselineBps: 5000 }] }, true);
  assert.equal(exam.status, 201);
  const values = [8000, 2000]; const salt = randomBytes(32).toString('hex'); const hash = commitmentHash(values, salt);
  const commit = await req('POST', `/api/exams/${exam.body.id}/commit`, { agentId: agent.body.id, hash, signature: signed(canonicalMessage('commit', [exam.body.id, agent.body.id, hash])) });
  assert.equal(commit.status, 201);
  const secondKeys = generateKeyPairSync('ed25519');
  const otherName = 'Vector';
  const otherPublic = secondKeys.publicKey.export({ format: 'der', type: 'spki' }).toString('base64');
  const otherSign = text => sign(null, Buffer.from(text), secondKeys.privateKey).toString('base64');
  const otherAgent = await req('POST', '/api/agents', { name: otherName, modelVersion, publicKey: otherPublic, signature: otherSign(canonicalMessage('register', [otherName, modelVersion])) });
  assert.equal(otherAgent.status, 201);
  const otherHash = commitmentHash([5000,5000], 'c'.repeat(64));
  assert.equal((await req('POST', `/api/exams/${exam.body.id}/commit`, { agentId: otherAgent.body.id, hash: otherHash, signature: otherSign(canonicalMessage('commit', [exam.body.id, otherAgent.body.id, otherHash])) })).status, 201);
  const duplicate = await req('POST', `/api/exams/${exam.body.id}/commit`, { agentId: agent.body.id, hash, signature: signed(canonicalMessage('commit', [exam.body.id, agent.body.id, hash])) });
  assert.equal(duplicate.status, 409);
  const revealRequest = { agentId: agent.body.id, probabilities: values, salt, signature: signed(canonicalMessage('reveal', [exam.body.id, agent.body.id, hash])) };
  assert.equal((await req('POST', `/api/exams/${exam.body.id}/reveal`, revealRequest)).status, 409);
  now += 121000;
  assert.equal((await req('POST', `/api/exams/${exam.body.id}/reveal`, { ...revealRequest, probabilities: [8000, 4000] })).status, 401);
  assert.equal((await req('POST', `/api/exams/${exam.body.id}/reveal`, revealRequest)).status, 200);
  assert.equal((await req('POST', `/api/exams/${exam.body.id}/reveal`, revealRequest)).status, 409);
  now += 240000;
  const resolution = await req('POST', `/api/admin/exams/${exam.body.id}/resolve`, { resolutions: [{ outcome: true, sourceEvidence: 'source A @ timestamp' }, { outcome: false, sourceEvidence: 'source B @ timestamp' }] }, true);
  assert.equal(resolution.status, 200);
  assert.equal(resolution.body.receipts.length, 1);
  assert.deepEqual(resolution.body.missed, [otherAgent.body.id]);
  const examPublic = (await req('GET', `/api/exams/${exam.body.id}`)).body;
  assert.equal(examPublic.missed[0].agentName, otherName);
  const receipt = (await req('GET', `/api/receipts/${resolution.body.receipts[0]}`)).body;
  assert.equal(receipt.score.brier, .04);
  assert.deepEqual(score(values, [true,false], [5000,5000]).sum, receipt.score.sum);
  const verified = (await req('GET', `/api/verify/${receipt.id}`)).body;
  assert.equal(verified.signatureValid, true);
  assert.equal(verified.commitmentValid, true);
  assert.equal(verified.scoreValid, true);
  assert.equal(verified.chain.status, 'not_anchored');
  const competence = (await req('GET', `/api/agents/${agent.body.id}/competence?domain=BTC`)).body;
  assert.equal(competence.resolvedCount, 2);
  assert.equal(competence.brier, .04);
  assert.equal(competence.evidenceLevel, 'limited sample');
  const page = await fetch(base + '/');
  assert.equal(page.status, 200);
  assert.match(await page.text(), /PROVEN/);
  const persisted = await new Store(dir).init();
  assert.equal(persisted.state.receipts.length, 1);
});

test('commitment hash binds every probability and salt', () => {
  const salt = 'a'.repeat(64);
  assert.notEqual(commitmentHash([1234, 5678], salt), commitmentHash([1234, 5679], salt));
  assert.notEqual(commitmentHash([1234, 5678], salt), commitmentHash([1234, 5678], 'b'.repeat(64)));
  assert.throws(() => commitmentHash([10001], salt));
});

test('Sui adapter constructs exam, commitment and score transactions', async () => {
  const chain = new SuiAnchor({});
  chain.enabled = true;
  chain.packageId = '0x123';
  const calls = [];
  chain.execute = async tx => {
    calls.push(tx.getData().commands[0].MoveCall.function);
    const type = ['Exam', 'Commitment', 'ExperienceReceipt'][calls.length - 1];
    const objectId = `0x${calls.length}`;
    return { digest: `tx-${type}`, effects: { changedObjects: [{ idOperation: 'Created', objectId }] }, objectTypes: { [objectId]: `0x123::proven::${type}` } };
  };
  const exam = { questionDigest: 'a'.repeat(64), questions: [{baselineBps:5000},{baselineBps:5000}], cutoffAt: new Date(Date.now()+1e6).toISOString(), revealUntil: new Date(Date.now()+2e6).toISOString(), resolveAfter: new Date(Date.now()+3e6).toISOString(), chainExamId: '0x1', resolutions: [{outcome:true},{outcome:false}] };
  assert.equal((await chain.createExam(exam)).objectId, '0x1');
  const entry = { hash: 'b'.repeat(64), agentId: 'agent-id', modelHash: 'c'.repeat(64), chainCommitId: '0x2', probabilities: [8000,2000], salt: 'd'.repeat(64) };
  assert.equal((await chain.commit(exam, entry)).objectId, '0x2');
  assert.equal((await chain.result(exam, entry, {resolutionDigest:'e'.repeat(64)})).objectId, '0x3');
  assert.deepEqual(calls, ['create_exam','commit','record_result']);
});
